services:
  ai-hedge-fund:
    container_name: ai-hedge-fund
    image: ceramicwhite/ai-hedge-fund:arm64
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./:/ai-hedge-fund
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: poetry run python src/main.py --ticker PLTR